getresults_result/urls.py
from django.conf.urls import url
from getresults_result.views import (
    ResultSectionView, UnvalidatedResultsView, UnreleasedResultsView,
    ResultValidateView, ResultReleaseView, ResultReleaseHistoryView)

urlpatterns = [
    url(r'(?P<section_title>(unvalidated))/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$', ResultValidateView.as_view(), name='validated_result_url'),
    url(r'(?P<section_title>(unreleased))/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$', ResultReleaseView.as_view(), name='released_result_url'),
    url(r'unvalidated/$', UnvalidatedResultsView.as_view(), name='unvalidated_results_url'),
    url(r'unreleased/$', UnreleasedResultsView.as_view(), name='unreleased_results_url'),
    url(r'history/(?P<section_title>(released))/$', ResultReleaseHistoryView.as_view(), name='released_results_history_url'),
    url(r'', ResultSectionView.as_view(), name='result_home_url'),
]

getresults_result/models.py
from uuid import uuid4
from django.db import models
from django.utils import timezone

from simple_history.models import HistoricalRecords as AuditTrail
from edc_base.model.models import BaseUuidModel

from getresults_identifier.result_identifier import ResultIdentifier
from getresults_order.models import Order, Utestid

from .choices import RELEASE_OPTIONS
from .constants import (
    ACCEPT, CANCEL, REPEAT, IGNORE, PENDING, PARTIAL, VALIDATED, CANCELLED,
    RELEASED, RELEASE, REVIEW, REPEATED)
from .managers import ResultManager

VALIDATION_STATUS = (
    (PENDING, 'Pending'),
    (PARTIAL, 'Partial'),  # set by system if some result items accepted/cancelled but not all
    (VALIDATED, 'Validated'),  # set by system if all result items accepted/cancelled
    (CANCELLED, 'Cancelled'),  # set by system if all result items cancelled
)

RELEASE_STATUS = (
    (PENDING, 'Pending'),
    (PARTIAL, 'Partial'),  # set by user if some accepted/cancelled AND some to be repeated
    (RELEASED, 'Released'),  # set by user if all accepted/cancelled
    (REPEATED, 'Repeated'),  # set by system if all cancelled
    (CANCELLED, 'Cancelled'),  # set by system if all cancelled
)


RESULT_ITEM_VALIDATION = (
    (ACCEPT, 'Accept'),  # flags order item as complete
    (REPEAT, 'Repeat'),  # flags order item ???
    (CANCEL, 'Cancel'),  # flags order item as cancelled
    (IGNORE, 'Ignore'),  # does nothing
    (PENDING, 'Pending'),  # initial state
)


RESULT_ITEM_RELEASE = (
    (PENDING, 'Pending'),  # set by no action or ignore
    ('release', 'Release'),  # set by user if accepted
    (REPEAT, 'Repeat'),  # set by system if repeat
    (CANCEL, 'Cancel'),  # set by system if cancel
)


class Result(BaseUuidModel):

    result_identifier = models.CharField(
        max_length=25,
        null=True)

    order = models.ForeignKey(Order)

    specimen_identifier = models.CharField(
        max_length=25,
        null=True)

    collection_datetime = models.DateTimeField(null=True)

    status = models.CharField(
        max_length=1,
        null=True,
        blank=True)

    analyzer_name = models.CharField(
        max_length=25,
        null=True)

    analyzer_sn = models.CharField(
        max_length=25,
        null=True)

    operator = models.CharField(
        max_length=25,
        null=True)

    last_exported = models.BooleanField(default=False)

    last_exported_datetime = models.DateTimeField(null=True, blank=True)

    validation_status = models.CharField(
        max_length=10,
        choices=VALIDATION_STATUS,
        default=PENDING)

    validation_datetime = models.DateTimeField(null=True, blank=True)

    release_status = models.CharField(
        max_length=10,
        choices=RELEASE_STATUS,
        default=PENDING)

    release_datetime = models.DateTimeField(null=True, blank=True)

    objects = ResultManager()

    history = AuditTrail()

    def __str__(self):
        return '{}: {}'.format(self.result_identifier, str(self.order))

    def save(self, *args, **kwargs):
        self.result_identifier = self.result_identifier or ResultIdentifier(self.order.order_identifier)
        super(Result, self).save(*args, **kwargs)

    def get_validation_status(self, result_items):
        lst = []
        for result_item in result_items:
            lst.append(result_item.status)
        if all([l == ACCEPT for l in lst]):
            return VALIDATED
        elif all([l == CANCEL for l in lst]):
            return CANCELLED
        elif all([l == REPEAT for l in lst]):
            return REPEATED
        elif all([l == IGNORE for l in lst]):
            return PENDING
        elif any([l == ACCEPT for l in lst]):
            return PARTIAL
        else:
            return PENDING

    class _Meta:
        app_label = 'getresults_result'
        db_table = 'getresults_result'
        unique_together = ('result_identifier', 'collection_datetime')


class ResultItem(BaseUuidModel):

    result = models.ForeignKey(Result)

    utestid = models.ForeignKey(Utestid)

    value = models.CharField(
        max_length=25,
        null=True)

    raw_value = models.CharField(
        max_length=25,
        null=True)

    quantifier = models.CharField(
        max_length=3,
        null=True)

    result_datetime = models.DateTimeField(
        null=True)

    status = models.CharField(
        max_length=10,
        choices=RESULT_ITEM_VALIDATION,
        default=PENDING)

    sender = models.CharField(
        max_length=25,
        null=True,
        help_text='analyzer or instrument')

    source = models.CharField(
        max_length=250,
        null=True,
        help_text='For example, \'filename\' for CSV or \'ASTM\'')

    validation_comment = models.CharField(
        max_length=25,
        null=True,
        blank=True)

    validation_datetime = models.DateTimeField(null=True)

    release_status = models.CharField(
        max_length=10,
        choices=RELEASE_OPTIONS,
        null=True)

    release_datetime = models.DateTimeField(null=True, blank=True)

    comment = models.CharField(
        max_length=100,
        null=True,
        blank=True)

    history = AuditTrail()

    def __str__(self):
        return '{}: {}'.format(str(self.utestid), str(self.result))

    class Meta:
        app_label = 'getresults_result'
        db_table = 'getresults_resultitem'
        unique_together = ('result', 'utestid', 'result_datetime')


class Release(BaseUuidModel):

    result = models.ForeignKey(Result)

    release_datetime = models.DateTimeField(
        default=timezone.now)

    status = models.CharField(
        max_length=25, blank=True,
        choices=RELEASE_OPTIONS)

    comment = models.CharField(
        max_length=25,
        null=True,
        blank=True)

    reference = models.CharField(
        max_length=36,
        default=uuid4,
        editable=False)

    history = AuditTrail()

    def __str__(self):
        return '{}: {}'.format(self.result.result_identifier, self.reference)

    def update_result(self):
        if self.status == RELEASE:
            self.result.release_status = RELEASED
            self.result.release_datetime = timezone.now()
        elif self.status == REVIEW:
            self.result.validation_status = REVIEW
            self.result.release_datetime = None
        elif self.status == CANCELLED:
            self.result.release_status = RELEASED
            self.result.release_datetime = timezone.now()
        else:
            self.result.release_status = PENDING
            self.result.release_datetime = None
        self.result.save()
        return self.result

    class Meta:
        app_label = 'getresults_result'
        db_table = 'getresults_release'


class Validate(BaseUuidModel):
    """Model to track the validation reference per result item in a result."""

    result_item = models.ForeignKey(ResultItem)

    validate_datetime = models.DateTimeField(
        default=timezone.now)

    status = models.CharField(
        max_length=25,
        # choices=VALIDATE_OPTIONS
    )

    comment = models.CharField(
        max_length=25,
        null=True,
        blank=True)

    reference = models.CharField(
        max_length=36,
        default=uuid4,
        editable=False)

    release = models.ForeignKey(Release, null=True, editable=False)

    released = models.BooleanField(default=False)

    history = AuditTrail()

    def __str__(self):
        return '{}: {}'.format(self.result_item.utestid, self.reference)

    def save(self, *args, **kwargs):
        self.released = True if self.release else False
        super(Validate, self).save(*args, **kwargs)

    class Meta:
        app_label = 'getresults_result'
        db_table = 'getresults_validate'

getresults_result/result_report/forms/result_search_form.py
from django import forms


class ResultSearchForm(forms.Form):
    result_search_term = forms.CharField(
        max_length=35,
        label="",
        help_text="enter all or part of a order number, sample identifier, patient identifier, etc",
        error_messages={'required': 'Please enter a search term.'},
        )

getresults_result/result_report/forms/search_form.py
from django import forms


class SearchForm(forms.Form):

    search_term = forms.CharField(
        max_length=35,
        label="Search",
        help_text="enter all or part of a order number, sample identifier, patient identifier, etc",
        error_messages={'required': 'Please enter a search term.'},
    )

getresults_result/result_report/views/view_result.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth.decorators import login_required

from ...models import Result
from ..classes import ResultContext
from django.views.generic.edit import FormView
from getresults_result.result_report.forms.result_search_form import ResultSearchForm
from django.utils.decorators import method_decorator


class SearchForm(FormView):

    template = 'search_form.html'
    form_class = ResultSearchForm
    field = '__all__'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return FormView.dispatch(self, request, *args, **kwargs)


@login_required
def view_result(request, **kwargs):

    result_identifier = kwargs.get('result_identifier')
    template = 'result_report.html'
    if result_identifier is not None:
        result_context = ResultContext(result_identifier=result_identifier)
        return render_to_response(
            template,
            result_context.context,
            context_instance=RequestContext(request)
        )


def render_search(**kwargs):
    return Result.objects.filter(result_identifier=kwargs['search_term'])

getresults_result/result_report/views/view_result_as_pdf.py
import os
import subprocess
import cStringIO as StringIO
import ho
import pisa as pisa
from math import ceil, trunc
from reportlab.pdfgen import canvas
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from lis.specimen.lab_result.models import Result
from lis.specimen.lab_result_item.models import ResultItem
from ..classes import ResultContext


@login_required
def view_result_as_pdf(request, **kwargs):
    section_name = kwargs.get('section_name')
    search_name = "result"
    result_identifier = kwargs.get('result_identifier')
    template = 'result_report_pdf.html'
    num_items_last_page = 18
    num_items_first_page = 13
    num_items_per_page = 23
    total_page_number = 1
    result = get_object_or_404(Result, result_identifier=result_identifier)
    items = ResultItem.objects.filter(result=result)
    num_items = items.count()
    if num_items > num_items_first_page:
        if (num_items - num_items_first_page) > num_items_last_page:
            num_items_other = num_items - num_items_first_page - num_items_last_page
            total_page_number += trunc(ceil(num_items_other / float(num_items_per_page)))
        else:
            total_page_number = 2
    if result_identifier:
        result_context = ResultContext(result_identifier)
        context = result_context.context
    else:
        context = {}
    context['pagesize'] = 'A4',
    context['total_page_number'] = total_page_number
    context['action'] = "print"
    file_data = render_to_string(template, context, RequestContext(request))
    myfile = StringIO.StringIO()
    pisa.CreatePDF(file_data, myfile)
    myfile.seek(0)
    # Create the HttpResponse object with the appropriate PDF headers.
    response = HttpResponse(myfile.getvalue(), mimetype='application/pdf')
    response['Content-Disposition'] = "attachment; filename=%s.pdf" % (result.result_identifier)
    return response


def batch_print_result_as_pdf(**kwargs):
    template = 'result_report_pdf.html'
    #result_ids = ['1240636-01','1242053-01','1241852-01','1242079-01','1241851-01']
    result_ids = ['1240636-01', '1242053-01']
    for result_identifier in result_ids:
        print_result_as_pdf(result_identifier, template)
    return


def print_result_as_pdf(result_identifier, template):
    section_name = 'result'
    search_name = 'result'
    num_items_last_page = 18
    num_items_first_page = 13
    num_items_per_page = 23
    total_page_number = 1

    if result_identifier is not None:
        file_name = "/home/pmotshegwa/sources/printed_results/%s.pdf" % (result_identifier)
        file = open(file_name, "wb")

        result = get_object_or_404(Result, result_identifier=result_identifier)
        items = ResultItem.objects.filter(result=result)

        num_items = items.count()

        if num_items > num_items_first_page:
            if (num_items - num_items_first_page) > num_items_last_page:
                num_items_other = num_items - num_items_first_page - num_items_last_page
                total_page_number += trunc(ceil(num_items_other / float(num_items_per_page)))
            else:
                total_page_number = 2
        if result_identifier:
            result_context = ResultContext(result_identifier)
            context = result_context.context
        else:
            context = {}
        context['pagesize'] = 'A4',
        context['total_page_number'] = total_page_number
        context['action'] = "print"
        file_data = render_to_string(template, payload,)
        myfile = StringIO.StringIO()
        pdf = pisa.CreatePDF(file_data, myfile)
        if pdf.err:
            print "*** %d ERRORS OCCURED" % pdf.err
        else:
            # Write pdf file to disk
            file.write(myfile.getvalue())
            file.close()
            command = "lp {0}".format(file_name)

            try:
                p = subprocess.Popen(command, shell=True)
                pid, sts = os.waitpid(p.pid, 0)
            except subprocess.CalledProcessError, e:
                print "Error", e.returncode
                print e.output
    return

getresults_result/templates/getresults_result/home.html
{% extends "section.html" %}

{% load staticfiles %}

{% load crispy_forms_tags %}


{% block section_sidebar %}
	<h5 class="sub-header">Results</h5>
         <ul class="nav nav-sidebar">
           <li><a href="/result/search/">Search</a></li>
           <li><a href="/result/import/">Import</a></li>
           <li><a href="/result/enter/">Enter</a></li>
           <li><a href="/result/unvalidated/">Validate</a></li>
           <li><a href="/result/unreleased/">Release</a></li>
           <li><a href="/result/history/released/">Released</a></li>
         </ul>
{% endblock section_sidebar %}

{% block section_labels%}
    <div class="col-xs-6 col-sm-3 placeholder">
      <h4>Enter</h4>
      <span class="text-muted">Enter a result</span>
    </div>
    <div class="col-xs-6 col-sm-3 placeholder">
      <h4>Import</h4>
      <span class="text-muted">Import results from an analyzer</span>
    </div>
    <div class="col-xs-6 col-sm-3 placeholder">
      <h4>Validate</h4>
      <span class="text-muted">Validate incoming results</span>
    </div>
    <div class="col-xs-6 col-sm-3 placeholder">
      <h4>Release</h4>
      <span class="text-muted">Release one or more validated results</span>
    </div>
{% endblock section_labels %}

getresults_result/templates/getresults_result/result_list.html
{% extends 'getresults_result/home.html'%}
{% load crispy_forms_tags %}

{% block section_body_title %}<h3 class="sub-header">{{ section_title|capfirst }}</h3>{% endblock section_body_title %}

{% block section_labels%}{% endblock section_labels%}

{% block section_header %}
    <tr>
      <th>#</th>
      <th>Result</th>
      <th>Panel</th>
      <th>Analyzer</th>
      <th>Date</th>
      <th>Order</th>
      <th>Validated</th>
      <th>Released</th>
      <th>Op</th>
    </tr>
{% endblock%}

{% block section_rows %}
	{% for obj in result_list %}
	  <tr>
	    {% if is_paginated %}
	    	<td>{{ forloop.counter|add:page_obj.start_index|add:-1 }}</td>
	    {% else %}
	    	<td>{{ forloop.counter }}</td>
	   	{% endif %}
	    <td><a href="{% url 'admin:getresults_result_result_change' obj.id %}?next={{ request.path }}">{{ obj.result_identifier }}</a></td>
	    <td>{{ obj.order.order_panel }}</td>
	    <td>{{ obj.analyzer_sn }}</td>
	    <td>{{ obj.collection_datetime|date:"Y-m-d"}}</td>
	    <td>{{ obj.order.order_identifier }}</td>
	    <td>{% if obj.validation_status == 'validated' %}{{ obj.validation_datetime|date:"Y-m-d"}}{% else %}<a href="{{ request.path }}{{ obj.pk }}/">{{ obj.get_release_status_display }}</a>{% endif %}</td>
	    <td>{% if obj.validation_status == 'validated' %}<a href="{{ request.path }}{{ obj.pk }}/">{{ obj.get_release_status_display }}</a>{% else %}{{ obj.get_release_status_display }}{% endif %}</td>
	    <td>{{ obj.operator }}</td>
	    <td></td>
	  </tr>
	{% endfor %}
{% endblock%}

getresults_result/templates/getresults_result/result_release.html
{% extends 'getresults_result/home.html'%}

{% load crispy_forms_tags %}

{% block section_labels%}{% endblock section_labels%}


{% block section_body_title %}<h3 class="sub-header">Unreleased Result for Order {{ result.order.order_identifier }}</h3>{% endblock section_body_title %}


{% block section_header%}
	<thead>
    <tr>
	<th>#</th>
	<th>Analyte</th>
	<th><div class="text-right">Value</div></th>    
	<th>Ref</th>
	<th>Flags</th>
	<th>Date</th>
	<th>Validation</th>
	<th>Comment</th>
	<th>#</th>
    </tr>
	</thead>
	<tbody>
{% endblock section_header%}


{% block section_rows %}
	{% for result_item in page_obj %}
		<tr>
		<td>{{ forloop.counter }}</td>
		<td>{{ result_item.utestid.name }}</td>
		<td><div class="text-right">{% if result_item.quantifier != '=' %}{{ result_item.quantifier }}{% endif %}{{ result_item.value }}&nbsp;{{ result_item.utestid.units|default:'' }}</div></td>
		<td>ref?</td>
		<td>flag?</td>
		<td>{{ result_item.result_datetime|date:"Y-m-d" }}</td>                
		<td>{{ result_item.status }}&nbsp;|&nbsp;{{ result_item.validation_datetime|date:"Y-m-d" }}&nbsp;{{ result_item.operator }}</td>                
		<td>{{ result_item.comment }}</td>     
  		<td>{{ forloop.counter }}</td>
  		</tr>
    {% endfor %}
    </tbody>
	</table>
{% crispy form %}
<table><tbody>
{% endblock section_rows %}

getresults_result/templates/getresults_result/result_validation.html
{% extends 'getresults_result/home.html'%}
{% load crispy_forms_tags %}

{% block section_labels%}{% endblock section_labels%}

{% block section_body_title %}<h3 class="sub-header">{{ section_title|capfirst }}</h3>{% endblock section_body_title %}

{% block section_body_one %}
<div class="table-responsive">
<table class="table table-striped">
<thead>
<th>Visit</th> 
<th>Collection</th> 
<th>Condition</th>
<th>Aliquot</th>     
<th>Ordered</th>     
<th>Order</th>     
</thead>
<tbody>
  <tr>
     <td>{{ visit }}</td>             
     <td>{{ order.aliquot.receive.collection_datetime|date:"Y-m-d H:i" }}</td>             
     <td>{{ order.aliquot.aliquot_condition }}</td>
     <td>{{ order.aliquot.aliquot_identifier }}</A></td>
     <td>{{ order.order_datetime|date:"Y-m-d" }}</td>             
     <td>{{ order.order_identifier }}</td>             
    </tr>                           
</tbody>
</table>
</div>
{% endblock section_body_one %}

{% block section_body_table %}
	<form id="id_validation_form" action="{{ request.path }}" method="POST">
	{% csrf_token %}
	{{ validation_formset.management_form }}
	<table class="table table-striped">
	<thead>
    <tr>
	<th>#</th>
	<th>Analyte</th>
	<th><div class="text-right">Value</div></th>    
	<th>Ref</th>
	<th>Flags</th>
	<th>Date</th>
	<th>Validation</th>
	<th>Comment</th>
	<th>#</th>
    </tr>
	</thead>
	<tbody>
	{% for form in validation_formset %}
	  <tr>
	    {% if is_paginated %}
	    	<td>{{ forloop.counter|add:page_obj.start_index|add:-1 }}</td>
	    {% else %}
	    	<td>{{ forloop.counter }}</td>
	   	{% endif %}
		<td>{{ form.instance.utestid }}</td> 
		<td><div class="text-right">{% if form.quantifier.value != '=' %}{{ form.quantifier.value }}{% endif %}{{ form.value.value }}&nbsp;{{ form.utestid.units|default:'' }}</div></td>
		<td>ref?</td>
		<td>flag?</td>
		<td>{{ form.result_datetime.value|date:"Y-m-d" }}</td>                
		<td>
			<div id='div-id-validation_status'>
			<span id="{{ accept_label }}_{{ forloop.counter|add:-1 }}" class="glyphicon glyphicon-ok text-muted" onclick="func_validation_status('{{ accept_label }}', {{ forloop.counter|add:-1 }})" ></span>
			<span id="{{ repeat_label }}_{{ forloop.counter|add:-1 }}" class="glyphicon glyphicon glyphicon-repeat text-muted" onclick="func_validation_status('{{ repeat_label }}', {{ forloop.counter|add:-1 }})"></span>
			<span id="{{ cancel_label }}_{{ forloop.counter|add:-1 }}" class="glyphicon glyphicon-remove text-muted" onclick="func_validation_status('{{ cancel_label }}', {{ forloop.counter|add:-1 }})"></span>
			<span id="{{ ignore_label }}_{{ forloop.counter|add:-1 }}" class="glyphicon glyphicon-question-sign text-muted" onclick="func_validation_status('{{ ignore_label }}', {{ forloop.counter|add:-1 }})"></span>
			<span id="id_validation_status_text_{{ forloop.counter|add:-1 }}" name="validation_status_text_{{ forloop.counter|add:-1 }}" class='text-danger bg-danger'>{{ form.status.value|default:"" }}</span>
			</div>
		</td>
			{{ form }}
	    {% if is_paginated %}
	    	<td>{{ forloop.counter|add:page_obj.start_index|add:-1 }}</td>
	    {% else %}
	    	<td>{{ forloop.counter }}</td>
	   	{% endif %}
	  </tr>
	{% endfor %}
	</tbody>
	</table>
	<!-- validation_form  -->{% crispy validation_form %}<!-- end validation_form  -->
	<!-- navigation_form  -->{% crispy navigation_form %}<!-- end navigation_form  -->
	</form>

	<script>
		document.addEventListener("DOMContentLoaded", function() {func_set_validation_status();});	
	</script>

{% endblock section_body_table %}